name: Business
favicon: null
layout_spectrum: 0.75845209765248
typography_spectrum: 0.7551085334271193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.5973856505006552
  lightness: 0.9978466236498207
  saturation: 0.09787142835557461
  rhythmicContrast: 0.8683425423223525
purpose:
  - name: engagement
    item: 88a86150-915c-408c-9097-d592983d5ba9
    url: null
