name: null
favicon: null
layout_spectrum: 0.43956
typography_spectrum: 0.40447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#11110f'
    - '#cfd0cb'
    - '#606165'
    - '#a7a7a5'
    - '#323426'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: engagement
    item: null
    url: null
